setting:
# ; browser:使用的浏览器，port: 端口
 browser: chrome
 port: 3000

time:
# ; start_time表示开始抢场地时间，默认为11:59:55，在这个时间start_time前一分钟会先登录等待
# ; finish_time表示结束时间
# ; 在start_time与finish_time之间会尝试进行抢场地操作，如果操作失败，会一直刷新页面
# ; delay_day表示抢几天之后的场地
  execute_start_time: 11:59:55
  execute_finish_time: 12:00:05
  delay_day: 3


wechat:
#; wechat_notice：是否开启微信通知
#; True/False，1/0，yes/no
  wechat_notice: False
  rsa_encrypt: False
#; TOKEN; 企业ID，应用ID
  TOKEN:
  CORP_ID: 
  AGENT_ID: 
  CORP_SERECT:
  PROXY: 
  EncodingAESKey: 

operate:
# ; mode:抢场地模式：0为单进程抢，会选择所有场地一起提交；
# ;1为多进程抢所需场地，比如需要两个时间段就会有两个进程；
# ;2为多进程抢所有场地，会使用多个进程抢所需时段场地，比如需要2个时段，10片场地备选，就会有2*10=20个进程同时抢
  mode: 0
